Online-Ceramics-Store/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using Online_Ceramics_Store.Models;
using System.Data;
using System.Text.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Online_Ceramics_Store.Controllers
{
    public class ProductsController : Controller
    {
        private IConfiguration _configuraion;
        private readonly string _connectionString = "";
        public ProductsController(IConfiguration configuration)
        {
            _configuraion = configuration;
            _connectionString = _configuraion.GetConnectionString("Default");
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult detailByName(string nameDetail)
        {
            Product product = null;
            using (MySqlConnection connection = new MySqlConnection(_connectionString))
            {
                connection.Open();
                string query = "SELECT * FROM ITEMS WHERE name = @nameDetail";
                using (MySqlCommand command = new MySqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@nameDetail", nameDetail);
                    using (MySqlDataReader reader = command.ExecuteReader())
                    {
                            if(reader.Read())
                            {
                                product = new Product()
                                {
                                    item_id = reader.GetInt32("item_id"),
                                    name = reader.GetString("name"),
                                    description = reader.GetString("description"),
                                    information = reader.GetString("information"),
                                    stock_quantity = reader.GetInt32("stock_quantity"),
                                    category_id = reader.GetInt32("category_id"),
                                    insale = reader.GetInt32("insale"),
                                    percent = reader.GetInt32("percent"),
                                    price = reader.GetInt32("price"),
                                };
                            }
                            
                        
                    }
                }
                connection.CloseAsync();
            }
            return RedirectToAction("detail", product);
            

        }
        public IActionResult detail(Product product)
        {
            int? cust_id = HttpContext.Session.GetInt32("cust_id");
            string? full_name = HttpContext.Session.GetString("full_name");
            ViewBag.CustId = cust_id;
            ViewBag.FullName = full_name;
            return View(product);
        }
        public IActionResult SearchProducts(string searchString)
        {
            List<Product> searchResults = new List<Product>();

            using (MySqlConnection connection = new MySqlConnection(_connectionString))
            {
                connection.Open();

                string query = "SELECT * FROM ITEMS WHERE name LIKE @searchString OR description LIKE @searchString";

                using (MySqlCommand command = new MySqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@searchString", "%" + searchString + "%");

                    using (MySqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Product product = new Product()
                            {
                                item_id = reader.GetInt32("item_id"),
                                name = reader.GetString("name"),
                                description = reader.GetString("description"),
                                information = reader.GetString("information"),
                                stock_quantity = reader.GetInt32("stock_quantity"),
                                category_id = reader.GetInt32("category_id"),
                                insale = reader.GetInt32("insale"),
                                percent = reader.GetInt32("percent"),
                                price = reader.GetInt32("price"),
                                
                            };
                            searchResults.Add(product);
                        }
                    }
                }
                connection.CloseAsync();
            }
            int? cust_id = HttpContext.Session.GetInt32("cust_id");
            string? full_name = HttpContext.Session.GetString("full_name");
            ViewBag.CustId = cust_id;
            ViewBag.FullName = full_name;
            return View("shop", searchResults);
        }

        public IActionResult fillterByPrice(int filterPriceMin, int filterPriceMax)
        {
            List<Product> allfillterProducts = new List<Product>();
            using (MySqlConnection connection = new MySqlConnection(_connectionString))
            {
                connection.Open();
                string query = "SELECT * FROM ITEMS";

                using (MySqlCommand command = new MySqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@filterPriceMin", filterPriceMin);
                    command.Parameters.AddWithValue("@filterPriceMax", filterPriceMax);
                    using (MySqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Product product = new Product()
                            {
                                item_id = reader.GetInt32("item_id"),
                                name = reader.GetString("name"),
                                description = reader.GetString("description"),
                                information = reader.GetString("information"),
                                stock_quantity = reader.GetInt32("stock_quantity"),
                                category_id = reader.GetInt32("category_id"),
                                insale = reader.GetInt32("insale"),
                                percent = reader.GetInt32("percent"),
                                price = reader.GetInt32("price"),
                            };
                            
                            if ((product.insale == 0 && product.price >= filterPriceMin && product.price <= filterPriceMax) ||  (product.insale == 1 && CalculateNewPrice(product) >= filterPriceMin && CalculateNewPrice(product) <= filterPriceMax)||filterPriceMin==0 && filterPriceMax==0)
                            {
                                allfillterProducts.Add(product);
                            }
                        }
                    }
                }
                connection.CloseAsync();
            }

            // Pass the filtered products to the view
            return View("shop", allfillterProducts);
        }
        // Method to calculate new price
        private int CalculateNewPrice(Product product)
        {
            return (int)(product.price - (product.price * product.percent / 100));
        }
        public IActionResult fillterBypopular()
        {
            List<Product> allfillterProducts = new List<Product>();
            using (MySqlConnection connection = new MySqlConnection(_connectionString))
            {
                connection.Open();
                string query = "SELECT * FROM ITEMS";

                using (MySqlCommand command = new MySqlCommand(query, connection))
                {
                   
                    using (MySqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Product product = new Product()
                            {
                                item_id = reader.GetInt32("item_id"),
                                name = reader.GetString("name"),
                                description = reader.GetString("description"),
                                information = reader.GetString("information"),
                                stock_quantity = reader.GetInt32("stock_quantity"),
                                quantity_purchased= reader.GetInt32("quantity_purchased"),
                                category_id = reader.GetInt32("category_id"),
                                insale = reader.GetInt32("insale"),
                                percent = reader.GetInt32("percent"),
                                price = reader.GetInt32("price"),
                            };

                            allfillterProducts = allfillterProducts.OrderByDescending(p => p.quantity_purchased).ToList();
                            allfillterProducts.Add(product);
                            
                        }
                    }
                }
                connection.CloseAsync();
            }

            // Pass the filtered products to the view
            return View("shop", allfillterProducts);
        }


        public IActionResult fillterbydecreaseprice()
        {
            List<Product> allfillterProducts = new List<Product>();
            using (MySqlConnection connection = new MySqlConnection(_connectionString))
            {
                connection.Open();
                string query = "SELECT * FROM ITEMS";

                using (MySqlCommand command = new MySqlCommand(query, connection))
                {
                    using (MySqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {

Online-Ceramics-Store/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;
using Online_Ceramics_Store.Models;
using System.Reflection;



// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Online_Ceramics_Store.Controllers
{
    public class ReferenceController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult contact()
        {
            ContactViewModel contact = new ContactViewModel();
            int? cust_id = HttpContext.Session.GetInt32("cust_id");
            string? full_name = HttpContext.Session.GetString("full_name");
            ViewBag.CustId = cust_id;
            ViewBag.FullName = full_name;
            return View("contact", contact);
        }


        [HttpPost]
        public IActionResult SendMessage(ContactViewModel contact)
        {
            if (ModelState.IsValid)
            {
                TempData["Success"] = "Your question has been sent successfully, you will receive an answer in the next few days to your email";
            }
            return View("contact", contact);
        }
        public IActionResult faqs()
        {
            int? cust_id = HttpContext.Session.GetInt32("cust_id");
            string? full_name = HttpContext.Session.GetString("full_name");
            ViewBag.CustId = cust_id;
            ViewBag.FullName = full_name;
            return View();
        }
    }

}

Online-Ceramics-Store/Views/ShoppingCart/orderSummary.cshtml
@model Online_Ceramics_Store.Models.CartModel
@using System.Data
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>EShopper - Bootstrap Shop Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row py-2 px-xl-5" style="background-color: #EDF1FF;">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="@Url.Action("faqs", "Reference")">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="@Url.Action("Contact", "Reference")">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="@Url.Action("Contact", "Reference")">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="@Url.Action("HomePage", "Home")" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold" style="color: black;">Kal Vahomer</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search" style="color: #D19C97;"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i class="fas fa-shopping-cart" style="color: #D19C97;"></i>
                    <span class="badge">0</span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between text-black w-100" style="color: black; background-color: #D19C97; height: 65px; margin-top: -1px; padding: 0 30px;" data-toggle="collapse" href="#navbar-vertical">
                    <h6 class="m-0">Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 180px">
                        <a href="" class="nav-item nav-link">Bowls</a>
                        <a href="" class="nav-item nav-link">Clay pots</a>
                        <a href="" class="nav-item nav-link">Jugs</a>
                        <a href="" class="nav-item nav-link">Cups</a>
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0" style="background-color: #EDF1FF;">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse" style="height: 65px;">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="@Url.Action("HomePage", "Home")" class="nav-item nav-link active">Home</a>
                            <a href="@Url.Action("shop", "Products")" class="nav-item nav-link">Shop</a>
                            <a href="shop.html" class="nav-item nav-link">Profile</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                            <a href="" class="nav-item nav-link">Login</a>
                            <a href="" class="nav-item nav-link">Register</a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->
    <!-- Page Header Start -->
    <div class="container-fluid mb-5" style="background-color: #EDF1FF;">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px; background-color: #EDF1FF; ">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Order Summary</h1>
            <h4 class="font-weight-semi-bold m-0">The order has been successfully completed and will be distributed in the coming days.</h4>
            <h4 calss="font-weight-semi-bold m-0">Thank you</h4>

        </div>
    </div>
    <!-- Page Header End -->
    <!-- Order Summary Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <!-- Display order details here -->
                <div class="mb-4">
                    <h4 class="font-weight-semi-bold mb-4">Order Details</h4>
                    <!-- Display order details using Razor syntax -->
                    <p>Order Number: @TempData["OrderId"]</p>
                    <p>Customer Name: @TempData["CustomerName"]</p>
                    <p>Order Date: @TempData["orderDate"]</p>
                    <p>Ship Date: @TempData["shipDate"]</p>
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Display total price paid and order number -->
                <div class="card border-secondary mb-5">
                    <div class="card-header border-0" style="background-color: #EDF1FF;">
                        <h4 class="font-weight-semi-bold m-0">Order Summary</h4>

                    </div>
                    <div class="card-body">
                        <!-- Display total price paid -->
                        <h5 class="font-weight-medium mb-3">Total Price Paid</h5>
                        <p>Total: $@TempData["TotalPrice"]</p>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <!-- Display order number -->
                        <p class="font-weight-bold">Order Number: @TempData["OrderId"]</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Order Summary End -->
    <!-- Footer Start -->
    <div class="container-fluid text-dark mt-5 pt-5" style="background-color: #EDF1FF;">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold" style="color: black;">Ceramics shop</h1>
                </a>
                <p>Welcome to Kal Vahomer Ceramics Studio, where creativity flourishes and stories are sculpted from clay. Join us to explore the art of ceramics through expert instruction and hands-on experiences for all skill levels..</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt mr-3" style="color: #D19C97;"></i>12 Har Boker, Mitzpe Ramon, ISRAEL</p>
                <p class="mb-2"><i class="fa fa-envelope mr-3" style="color: #D19C97;"></i>studiokalvahomer@gmail.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt mr-3" style="color: #D19C97;"></i>0509799089</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="@Url.Action("HomePage", "Home")"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="@Url.Action("shop", "Products")"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-dark mb-2" href="@Url.Action("cart", "ShoppingCart")"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="@Url.Action("checkout", "ShoppingCart")"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="@Url.Action("Contact", "Reference")"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-6 px-xl-0 text-center text-md-right">
                        <img class="img-fluid" src="~/Images/KalVahomer-5.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Kal Vahomer</a>
                </p>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top" style="background-color: #D19C97; border: hidden;"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
 
</body>

</html>